#image: gitpod/workspace-dotnet

image:
  file: .gitpod.Dockerfile

tasks:
  - init: dotnet build
    command: dotnet run

vscode:
  extensions:
    - muhammad-sammy.csharp@1.23.9:BMArOoGwWqKRrH6s4E2/AQ==